language: python
cache: pip
python: 2.7

sudo: false
dist: trusty
addons:
  apt:
    packages:
      - libxml2-utils

install:
  - cd exitwp
  - pip install --upgrade -r pip_requirements.txt

script:
  - ../build.sh
